# Generated by Django 3.2.13 on 2022-04-22 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='librabudget',
            name='location',
            field=models.CharField(default='6 october', max_length=200),
            preserve_default=False,
        ),
    ]
