# Generated by Django 3.2.13 on 2022-04-22 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_alter_librabudget_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librabudget',
            name='location',
            field=models.CharField(choices=[('6 OCTOBER', '6 OCTOBER SITE'), ('ABOU AWAIKE', 'ABOU AWAIKEL SITE')], max_length=20),
        ),
    ]
