# Generated by Django 3.2.13 on 2022-04-22 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_alter_librabudget_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='librabudget',
            name='reason1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='librabudget',
            name='location',
            field=models.CharField(choices=[('6 OCTOBER', '6 OCTOBER SITE'), ('ABOU AWAIKE', 'ABOU AWAIKEL SITE'), ('Libra', 'Libra Company')], max_length=20),
        ),
    ]
