# Generated by Django 3.2.13 on 2022-04-22 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_auto_20220422_2142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='librabudget',
            old_name='reason1',
            new_name='reason_all',
        ),
    ]
